import re
from typing import Dict

# English Word to Indic/Telugu Phonetic Pronunciation Dictionary
ENGLISH_PHONETIC_MAP: Dict[str, str] = {
    "actually": "యాక్చువల్లీ",
    "important": "ఇంపార్టెంట్",
    "topic": "టాపిక్",
    "feature": "ఫీచర్",
    "useful": "యూజ్‌ఫుల్",
    "especially": "ఎస్పెషల్లీ",
    "business": "బిజినెస్",
    "businesses": "బిజినెస్సెస్",
    "ready": "రెడీ",
    "let": "లెట్",
    "us": "అస్",
    "try": "ట్రై",
    "this": "దిస్",
    "new": "న్యూ",
    "voice": "వాయిస్",
    "synthesis": "సింథసిస్",
    "system": "సిస్టమ్",
    "hi": "హాయ్",
    "hello": "హలో",
    "welcome": "వెల్‌కమ్",
    "today": "టుడే",
    "first": "ఫస్ట్",
    "test": "టెస్ట్",
    "result": "రిజల్ట్",
    "work": "వర్క్",
    "working": "వర్కింగ్",
    "message": "మెసేజ్",
    "send": "సెండ్",
    "everyone": "ఎవ్రీవన్",
    "model": "మోడల్",
    "use": "యూజ్",
    "using": "యూజింగ్",
    "project": "ప్రాజెక్ట్",
    "user": "యూజర్",
    "users": "యూజర్స్",
    "admin": "అడ్మిన్",
    "dashboard": "డాష్‌బోర్డ్",
    "audio": "ఆడియో",
    "sound": "సౌండ్",
    "player": "ప్లేయర్",
    "speech": "స్పీచ్",
    "cloning": "క్లోనింగ్",
    "studio": "స్టూడియో",
    "quality": "క్వాలిటీ",
    "natural": "నాచురల్",
    "clear": "క్లియర్",
    "good": "గుడ్",
    "morning": "మార్నింగ్",
    "evening": "ఈవినింగ్",
    "night": "నైట్",
    "thank": "థాంక్",
    "you": "యూ",
    "please": "ప్లీజ్",
    "life": "లైఫ్",
    "future": "ఫ్యూచర్",
    "technology": "టెక్నాలజీ",
    "platform": "ప్లాట్‌ఫారమ్",
    "website": "వెబ్‌సైట్",
    "software": "సాఫ్ట్‌వేర్",
    "customer": "కస్టమర్",
    "customers": "కస్టమర్స్",
    "agent": "ఏజెంట్",
    "agents": "ఏజెంట్స్",
    "whatsapp": "వాట్సాప్",
    "integration": "ఇంటిగ్రేషన్",
    "application": "అప్లికేషన్",
    "plan": "ప్లాన్",
    "plans": "ప్లాన్స్",
    "subscription": "సబ్‌స్క్రిప్షన్",
    "payment": "పేమెంట్",
    "invoice": "ఇన్‌వాయిస్",
    "pricing": "ప్రైసింగ్",
    "create": "క్రియేట్",
    "generate": "జెనరేట్",
    "code": "కోడ్",
    "developer": "డెవలపర్",
    "tool": "టూల్",
    "tools": "టూల్స్",
    "support": "సపోర్ట్",
    "email": "ఈమెయిల్",
    "number": "నంబర్",
    "time": "టైమ్",
    "name": "నేమ్",
    "file": "ఫైల్",
    "folder": "ఫోల్డర్",
    "open": "ఓపెన్",
    "save": "సేవ్",
    "delete": "డిలీట్",
    "remove": "రిమూవ్",
    "add": "యాడ్",
    "edit": "ఎడిట్",
    "select": "సెలెక్ట్",
    "setting": "సెట్టింగ్",
    "settings": "సెట్టింగ్స్",
    "account": "అకౌంట్",
    "login": "లాగిన్",
    "logout": "లాగౌట్",
    "password": "పాస్‌వర్డ్",
    "token": "టోకెన్",
    "security": "సెక్యూరిటీ",
    "team": "టీమ్",
    "role": "రోల్",
    "error": "ఎర్రర్",
    "success": "సక్సెస్",
    "screen": "స్క్రీన్",
    "page": "పేజీ",
    "home": "హోమ్",
    "table": "టేబుల్",
    "chart": "చార్ట్",
    "report": "రిపోర్ట్",
    "data": "డేటా",
    "database": "డేటాబేస్",
    "server": "సర్వర్",
    "cloud": "క్లౌడ్",
    "speed": "స్పీడ్",
    "the": "ది",
    "to": "టు",
    "and": "అండ్",
    "of": "ఆఫ్",
    "for": "ఫర్",
    "in": "ఇన్",
    "on": "ఆన్",
    "at": "ఎట్",
    "by": "బై",
    "from": "ఫ్రమ్",
    "with": "విత్",
    "is": "ఇజ్",
    "it": "ఇట్",
    "or": "ఆర్",
    "an": "యాన్",
    "be": "బీ",
    "are": "ఆర్",
    "as": "యాజ్",
    "was": "వాజ్",
    "that": "ద్యాట్",
    "have": "హ్యావ్",
    "not": "నాట్",
    "one": "వన్",
    "all": "ఆల్",
    "were": "వర్",
    "we": "వీ",
    "when": "వెన్",
    "your": "యువర్",
    "can": "క్యాన్",
    "there": "దేర్",
    "which": "విచ్",
    "their": "దేర్",
    "if": "ఇఫ్",
    "do": "డూ",
    "will": "విల్",
    "each": "ఈచ్",
    "about": "ఎబౌట్",
    "how": "హౌ",
    "up": "అప్",
    "out": "అవుట్",
    "them": "దెమ్",
    "then": "దెన్",
    "she": "షీ",
    "many": "మెనీ",
    "some": "సమ్",
    "so": "సో",
    "these": "దీజ్",
    "would": "వుడ్",
    "other": "అదర్",
    "into": "ఇంటూ",
    "has": "హ్యాజ్",
    "more": "మోర్",
    "her": "హర్",
    "two": "టూ",
    "like": "లైక్",
    "him": "హిమ్",
    "see": "సీ",
    "time": "టైమ్",
    "could": "వుడ్",
    "no": "నో",
    "make": "మేక్",
    "than": "ద్యాన్",
    "been": "బీన్",
    "who": "హూ",
    "its": "ఇట్స్",
    "now": "నౌ",
    "my": "మై",
    "made": "మేడ్",
    "over": "ఓవర్",
    "did": "డిడ్",
    "down": "డౌన్",
    "only": "ఓన్లీ",
    "way": "వే",
    "find": "ఫైండ్",
    "may": "మే",
    "water": "వాటర్",
    "long": "లాంగ్",
    "little": "లిటిల్",
    "very": "వెరీ",
    "after": "ఆఫ్టర్",
    "words": "వర్డ్స్",
    "called": "కాల్డ్",
    "just": "జస్ట్",
    "where": "వేర్",
    "most": "మోస్ట్",
    "know": "నో",
}

SUFFIX_RULES = [
    (r"tion\b", "షన్"),
    (r"sion\b", "షన్"),
    (r"ment\b", "మెంట్"),
    (r"ing\b", "ింగ్"),
    (r"able\b", "ేబుల్"),
    (r"less\b", "లెస్"),
    (r"ness\b", "నెస్"),
    (r"ful\b", "ఫుల్"),
    (r"ly\b", "లీ"),
    (r"ed\b", "ెడ్"),
    (r"er\b", "ర్"),
    (r"est\b", "ెస్ట్"),
]

LETTER_RULES = [
    (r"sh", "ష్"),
    (r"ch", "చ్"),
    (r"th", "థ్"),
    (r"ph", "ఫ్"),
    (r"ck", "క్"),
    (r"ng", "ంగ్"),
    (r"qu", "క్వ్"),
    (r"ee", "ీ"),
    (r"ea", "ీ"),
    (r"oo", "ూ"),
    (r"ou", "ౌ"),
    (r"ow", "ౌ"),
    (r"ai", "ై"),
    (r"ay", "ే"),
    (r"a", "ా"),
    (r"e", "ె"),
    (r"i", "ి"),
    (r"o", "ో"),
    (r"u", "ు"),
    (r"b", "బ్"),
    (r"c", "క్"),
    (r"d", "డ్"),
    (r"f", "ఫ్"),
    (r"g", "గ్"),
    (r"h", "హ్"),
    (r"j", "జ్"),
    (r"k", "క్"),
    (r"l", "ల్"),
    (r"m", "మ్"),
    (r"n", "న్"),
    (r"p", "ప్"),
    (r"r", "ర్"),
    (r"s", "స్"),
    (r"t", "ట్"),
    (r"v", "వ్"),
    (r"w", "వ్"),
    (r"x", "క్స్"),
    (r"y", "య్"),
    (r"z", "జ్"),
]


class EnglishPronunciationProcessor:
    """
    Dedicated English Pronunciation Processor.
    Translates validated English spans into precise English phonetic representations
    that IndicF5 synthesizes as natural human-like English speech in the cloned voice.
    """

    @staticmethod
    def process_word(word: str) -> str:
        clean = word.lower().strip()
        if clean in ENGLISH_PHONETIC_MAP:
            return ENGLISH_PHONETIC_MAP[clean]

        res = clean
        for pat, repl in SUFFIX_RULES:
            res = re.sub(pat, repl, res)

        for pat, repl in LETTER_RULES:
            res = re.sub(pat, repl, res)

        return res

    @staticmethod
    def process_text(text: str) -> str:
        words_and_delims = re.findall(r"[a-zA-Z]+|[^a-zA-Z]+", text)
        result = []

        for item in words_and_delims:
            if re.match(r"^[a-zA-Z]+$", item):
                result.append(EnglishPronunciationProcessor.process_word(item))
            else:
                result.append(item)

        return "".join(result)

