export const ContextErrors = {
  USER_CONTEXT_NOT_FOUND: "USER_CONTEXT_NOT_FOUND",
  ORGANIZATION_CONTEXT_NOT_FOUND: "ORGANIZATION_CONTEXT_NOT_FOUND",
  PROJECT_CONTEXT_NOT_FOUND: "PROJECT_CONTEXT_NOT_FOUND",
  AGENT_CONTEXT_NOT_FOUND: "AGENT_CONTEXT_NOT_FOUND",
  INVALID_CONTEXT: "INVALID_CONTEXT",
};
