export const UploadPurpose = Object.freeze({
  PLATFORM_LOGO: "PLATFORM_LOGO",
  ORGANIZATION_LOGO: "ORGANIZATION_LOGO",
  PROFILE_PHOTO: "PROFILE_PHOTO",
  KNOWLEDGE_FILE: "KNOWLEDGE_FILE",
  KNOWLEDGE_LINK: "KNOWLEDGE_LINK",
});
