export const UploadPurpose = Object.freeze({
  PLATFORM_LOGO: "PLATFORM_LOGO",
  ORGANIZATION_LOGO: "ORGANIZATION_LOGO",
  PROFILE_PHOTO: "PROFILE_PHOTO",
  KNOWLEDGE_FILE: "KNOWLEDGE_FILE",
  KNOWLEDGE_LINK: "KNOWLEDGE_LINK",
  AI_VIDEO_CHARACTER_IMAGE: "AI_VIDEO_CHARACTER_IMAGE",
  AI_VIDEO_SCENE_IMAGE: "AI_VIDEO_SCENE_IMAGE",
  AI_VIDEO_SCENE_CLIP: "AI_VIDEO_SCENE_CLIP",
  AI_VIDEO_OUTPUT: "AI_VIDEO_OUTPUT",
});
